### PR TITLE
Fix error

### PR DESCRIPTION
**Pull request by franleplant**
- Fix corner case error when selecting the default option on the sub region select on the Time Zone selector directive

### CODE REVIEW

**Comment by srpabliyo** [comment]
:+1: but cannot accept this Coverage decreased (-0.61%), :stuck_out_tongue_winking_eye: , hehe no, it's reviewed ok!

**Comment by franleplant** [comment]
Jajajaja Pablo :smile_cat:

**Comment by kamuslhv** [comment]
I'm with @srpabliyo on this, that decrease in code coverage is unacceptable @franleplant :P 
Reviewed ok :+1:

**Comment by arvenil** [comment]
`Coverage decreased (-0.61%)` shame on you @franleplant ! Unacceptable ! :P

:sparkles::sparkles: :+1: :sparkles::sparkles:

**Pull request merged**
